baseURL = "/"
publishDir = "dist"
languageCode = "en-us"
title = "Jos de Jong"
copyright = "Copyright &copy; 2013-2025 <a href='https://josdejong.com'>Jos de Jong</a> &bull; powered by <a href='https://gohugo.io/'>Hugo</a> and <a href='https://pages.github.com/'>GitHub pages</a> &bull; background from <a href='https://www.technobuffalo.com/sites/technobuffalo.com/files/wp/2010/11/tb-wallpaper-blue-2560x1440.jpg'>technobuffalo</a>"

googleAnalytics = "UA-42777816-1"

disqusShortname = "josdejong"

[params]
  subtitle = "a blog about programming and web development"
  github="josdejong"
  linkedin="jos-de-jong-b1345615"
  feed="/index.xml"
  favicon = "favicon.jpg"
  custom_css = ["css/custom_style.css"]

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects"
    weight = 2

[[menu.main]]
    name = "About me"
    identifier = "about"
    url = "/about"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # to allow inline HTML
  [markup.highlight]
    style = "monokai"

[caches]
  [caches.images]
    dir = ':cacheDir/images'